export const smsBearerToken = {
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDU0NzQ3MDYsImlhdCI6MTcwMjg4MjcwNiwicm9sZSI6InRlc3QiLCJzdWIiOiI1OTI3In0.CSQOpkMichk0mMuazUDitEIz5xGeD_THiHfc0N_j54s',
};
